apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp1
  namespace: prod
  labels:
    app: flaskapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp1
  template:
    metadata:
      name: flasktemplate1
      labels:
        app: flaskapp1
    spec:
      containers:
      - image: nginx
        name: flaskcontainer
        ports:
        - containerPort: 5000
