name: Test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  KUBE_NAMESPACE: prod
  ECR_REPOSITORY: container_repo1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_and_deploy"
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout                                  
        uses: actions/checkout@v2
     
      - name: Configure AWS credentials                          
        uses: aws-actions/configure-aws-credentials@v1           
        with:                                                    
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}        
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
    
      - name: Check deployment status
        id: deploy_status
        uses: Consensys/kubernetes-action@master
        with:                                                                                                         
          args: get deploy -A
    
      - name: Print deployment status and ENV
        env:
          DEPLOY_STATUS: ${{ steps.deploy_status.outputs.result }}
          ENV333: httpd
        run: |
          echo  $DEPLOY_STATUS
          printf "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: flaskprod\n  namespace: prod\n  labels:\n    app: flaskprod\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: flaskprod\n  template:\n    metadata:\n      name: flasktemplate1\n      labels:\n        app: flaskprod\n    spec:\n      containers:\n      - image: ${{ env.ENV333 }}\n        name: flaskcontainer\n        ports:\n        - containerPort: 5000\n" > k8s.yaml
      
      - name: If true
        if: contains( env.DEPLOY_STATUS, 'flask1-deploy') == 'true'
        run: |
          echo "Deployment exists"
          echo ${{ steps.deploy_status.outputs.result }}
          
      - name: If false
        if: contains( env.DEPLOY_STATUS, 'flask1-deploy') != 'true'
        run: |
          cat k8s.yaml
      #  uses: kodermax/kubectl-aws-eks@master
      #  env:                                                                                                          
      #    RELEASE_IMAGE: httpd
      #  with:
      #    args: apply -f k8s_deploy.yaml
        #run: |
        #  echo "Deployment doesn't exist"
        #  echo ${{ steps.deploy_status.outputs.result }}
    
      #- name: Rollout new deployment to Kubernetes cluster                                                                            
      #  uses: Consensys/kubernetes-action@master
      #  if: contains(rollout status deploy flask1-deploy -n prod, 'NotFound') == 'true'
      #  with:                                                                                                         
      #    args: create deployment flaskapp1 --image=nginx -n prod
